# Generated by Django 4.0.4 on 2022-04-16 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0003_alter_faq_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='created',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='faq',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
