# Generated by Django 4.0.4 on 2022-04-19 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_alter_faq_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='last_updated_user',
            field=models.CharField(default=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'), max_length=10),
        ),
    ]
